### ISSUE TITLE
No connection to Sofar inverter 3.6ktlm-g2

### ISSUE THREAD

**Issue by ploman1973** [robbinjanssen/home-assistant-omnik-inverter#104]
I am trying to connect to my Sofar inverter with Wifi stick (serial 0528...). Al the the methods do not make a connection.

I can connect to my logger with 192.168.86.194/status.html and see this info in the source:

edit:
copy past part status.html deleted and added as attachment
[status html.txt](https://github.com/robbinjanssen/home-assistant-omnik-inverter/files/8417627/status.html.txt)

**Comment by robbinjanssen** [comment]
Hi @ploman1973, can you paste the complete status.html between ` ```  ` please? Did you add the `|` yourself or are they there?

**Comment by robbinjanssen** [comment]
Thanks, do you see any error whatsoever? Could it be that your HA has no access to that IP address?

**Comment by ploman1973** [comment]
Hello, the only error is the message that the site cannot be found. (see picture, I am sure user and password are correct) Both logger en Homeassistant are in my local network.
![Schermafbeelding 2022-04-05 135722](https://user-images.githubusercontent.com/22667224/161748815-f0475840-89e1-4569-b07b-279d3d3d181f.png)

**Comment by robbinjanssen** [comment]
@ploman1973, try using only the IP address (`192.168.68.194`) without HTTP and status.html as host, that should work :)

**Comment by ploman1973** [comment]
pfffff thought I had tried this already a 1000 times :). But not because this works. Thank you verry much
