### ISSUE TITLE
Question about Ginlong LAN stick - will it work?

### ISSUE THREAD

**Issue by Shadoweee77** [robbinjanssen/home-assistant-omnik-inverter#107]
Question about Ginlong LAN stick - will it work? Currently waiting for mine so can't test it, but maybe someone else has it running?
Thanks and sorry for putting this as an issue.

**Comment by robbinjanssen** [comment]
I think a few people have tried it, and some sticks work, some don't. 
Guess we'll find out when you get yours 😄  If it outputs the data via JSON, JS or HTML, we'll probably get it working!

**Comment by Shadoweee77** [comment]
Got it, thanks!
