### ISSUE TITLE
Solis inverter with YingZhen datalogger not working

### ISSUE THREAD

**Issue by Jessy142** [robbinjanssen/home-assistant-omnik-inverter#112]
When I try to add my Solis (Ginlong) inverter with YingZhen datalogger (WiFi stick) my HA tells me the following at the integration configuration.

> Opnieuw proberen in te stellen: A username and/or password is missing from the request

I have added it via the HTML way, I can reach the WiFi stick at status.html and it has a <script> tag with the webData.

HA log says the following: 
> Config entry 'Solis' for omnik_inverter integration not ready yet: A username and/or password is missing from the request; Retrying in background

I have filled in the username & password when I configured the integration in HA (default admin, admin)

![image](https://user-images.githubusercontent.com/26705979/171839989-dfe4a255-f818-4876-988e-cf1739c4c18e.png)
![image](https://user-images.githubusercontent.com/26705979/171840029-ef19ebb5-3210-4175-9b41-eb3f24f08412.png)
![image](https://user-images.githubusercontent.com/26705979/171839940-40a930b5-5d62-4394-b6d9-7c4ff931670b.png)

**Comment by klaasnicolaas** [comment]
We have found the bug and version 2.4.1 fixes the problem.
