### ISSUE TITLE
1. Request reads 0 total_energy, leading to overshoot when actual values are read

### ISSUE THREAD

**Issue by tilchl** [robbinjanssen/home-assistant-omnik-inverter#120]
## Detailed description
I have a Bosswerk MI600 which is read via HTML

The HA integration has a problem with the inverter "waking up". I belive the first request reads 0 kWh for Total and Today production. 
<img width="350" alt="Screenshot 2022-06-23 110643" src="https://user-images.githubusercontent.com/27765476/175262219-01be4c14-c01f-4207-abe2-565a8c7b28cc.png">

This in turn leads for the Energy Dash to display the second request as a plus of total. 
<img width="350" alt="Screenshot 2022-06-23 110643" src="https://user-images.githubusercontent.com/27765476/175262484-77b39668-1451-4ef9-9693-80c74cf66b24.png">

Normally I could use the `solar_energy_today` but I disabled all communications between the logger and china.
That way the logger does not get a new date to reset the `solar_energy_today`.

ideally a `solar_energy_total` of zero would be ignored if larger values are present. 
I don't know what db HA is using but it might support dropping queries with decreasing values for said key.
Otherwise a query of the last value is neccesary and only conditionally write the new value.

**Comment by robbinjanssen** [comment]
I think this is related to #51, I had similar problems with my inverter but they magically resolved themselves 🤷 
By caching the value and resetting it at 00:00, it should be good I think?

**Comment by klaasnicolaas** [comment]
Strange, we once made an exception that pops up when your day and total indicate 0 kwh. Precisely to prevent us from getting this kind of situation, I'm curious what the logs are when this happens 🤔

**Comment by tilchl** [comment]
I have already tried to analyze the TCP requests comming from the logger. But no luck.

I just dont want the logger to call home. I find it kind of alarming that it sends all meta information to the Solarmann API just by connecting it to a WiFi network.

Shame they dont share their modbus/TCP structure.
