### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by FrankyB1983** [robbinjanssen/home-assistant-omnik-inverter#122]
Sometimes I get strange overflows. For example. It work totally fine for a couple of days. And then I get a current power value of 76000 watts. My solar panels can only produce 1080 watts.

I use an omnik 1000TL

**Comment by FrankyB1983** [comment]
![Screenshot_20220717-091348](https://user-images.githubusercontent.com/23337049/179388106-e5981b0f-603a-46d3-a409-3cf9c0c4730f.png)

**Comment by robbinjanssen** [comment]
Go to you integrations, find the Omnik integration and click on the 3 dots. Then click on the "Download diagnostics" link, this file will provide all information :-)

**Comment by SebastianMornhinweg** [comment]
Happens sometimes for me too. The daily count will be taken as current production. So in HA i then see for this hour a high peak and the daily production is doubled. I use HTML with a Deye/Bosswerk MI 600.
![image](https://user-images.githubusercontent.com/99015912/198583740-93db15f6-1697-48ba-aba8-e0e68c938c36.png)

**Comment by robbinjanssen** [comment]
We haven't received any input on this issue. Feel free te reopen but please provide the requested diagnostics.
