### ISSUE TITLE
Very often I get unknown values

### ISSUE THREAD

**Issue by Dominion0815** [robbinjanssen/home-assistant-omnik-inverter#123]
Hi,

in my screenshots you see that my Bosswerk MI600 often has gaps with unknown values.
Is it possible to cache the last state insteat?

![Screenshot 2022-08-03 at 07-59-03 Übersicht – Home Assistant](https://user-images.githubusercontent.com/33466236/182535314-12ee48f5-31d7-46a7-951d-8590f32a163b.png)
![Screenshot 2022-08-03 at 07-58-22 Verlauf – Home Assistant](https://user-images.githubusercontent.com/33466236/182535323-b232c0ce-02e7-411a-81aa-fced197d2497.png)

Greetings
dominion

**Comment by MarijnS95** [comment]
Could be similar to (duplicate of) https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/100?

**Comment by Dominion0815** [comment]
oh yeah it is similar sorry.

My inverter is always accessible via wifi, only sometimes it does not output any values but displays "---" in the web interface.
I don't know if there is a query limit and a cache might help.
