### ISSUE TITLE
add Connectivity Status Binary Sensor

### ISSUE THREAD

**Issue by CFenner** [robbinjanssen/home-assistant-omnik-inverter#127]
I would like to see if my inverter is up & connected. 

## Detailed description

There is a `device_class: connectivity` which can be used to display this. 

<img width="334" alt="Bildschirmfoto 2022-09-06 um 19 47 02" src="https://user-images.githubusercontent.com/9592452/188704711-b5d4be9e-8182-442b-b9ac-dfeb3c9b4c95.png">
<img width="335" alt="Bildschirmfoto 2022-09-06 um 19 48 13" src="https://user-images.githubusercontent.com/9592452/188704712-8128e6d8-f87f-41c9-b433-c2644173b285.png">
<img width="1048" alt="Bildschirmfoto 2022-09-06 um 19 46 22" src="https://user-images.githubusercontent.com/9592452/188704699-b0f4667b-dfdc-4dd6-b952-8d3f9e428d94.png">

Meanwhile is solved this by adding a template sensor:

```yaml
name: Bosswerk Veranda Status
state: >-
  {% if states('sensor.bosswerk_veranda_solar_current_power') in ("unavailable", "unknown") -%}
    off
  {%- else -%}
    on
  {%- endif %}
device_class: connectivity
```

## Context

Use in automations.

**Comment by robbinjanssen** [comment]
So we could do this by checking "do receive data? e.g. status 200 OK?" -> UP, if not -> DOWN.
Is that something you could work with?

**Comment by MarijnS95** [comment]
Is this `unavailable`/`unknown` value thought up by HASS when the integration hasn't provided any value for said entity for some time? We were thinking about driving this connectivity status by a configurable timeout on the requests that are sent by this integration (i.e. we won't get any http 200 replies / data if the inverter is offline/disconnected - if that happens for a couple requests in a row the inverter is likely unreachable).

**Comment by CFenner** [comment]
> Is this `unavailable`/`unknown` value thought up by HASS when the integration hasn't provided any value for said entity for some time? 

I think that is how it works. The idea I had is that with a `connectivity` entity the status is even displayed when the device is not reachable.

**Comment by CFenner** [comment]
now during winter time my inverter is always offline. I would expect the integration to display this as the entities being unavailable. Also having a status entity would top here. 

![DBD8CD2E-25D0-4BB2-AB7E-DCFECD46D205](https://user-images.githubusercontent.com/9592452/206454917-f0b2b5bd-bcb0-4260-bf8b-977d688cdc1d.jpeg)

**Comment by robbinjanssen** [comment]
@CFenner does it show the image above after a restart of HA or a reload of the integration?

**Comment by CFenner** [comment]
Both
