### ISSUE TITLE
Inverter Omnik 3000TL not connecting

### ISSUE THREAD

**Issue by rulaan** [robbinjanssen/home-assistant-omnik-inverter#129]
Hi,

My 2nd omnik inverter is not connecting to HA (the first one, an Omniksol-2.5k-TL3-S bought in 2019 connected on first attempt). I tried the 4 options provided, and also tried the URL's mentioned.
JS => 404
JSON => 404
HTML => 404

The converter is an Omniksol 3000 TL bought in 2013. Has been connected to omnikportal, and is now connected to solarmanpv (so there is output to be read).

I am able to access the following page on the logger (after authenticating with a changed admin user and password):
http://<inverter_IP>/home.html

Any suggestions on making the connection work are welcome!

Thanks, Rudi.

**Comment by klaasnicolaas** [comment]
Have you also tried the TCP option?

**Comment by rulaan** [comment]
Yes

**Comment by robbinjanssen** [comment]
Hi @rulaan!

1. What happens when you access http://<inverter_IP>/js/status.js ?

2. Can you check your HTML source and see if there is any JS data? It should contain something like: https://github.com/klaasnicolaas/python-omnikinverter/blob/main/tests/fixtures/status.html

**Comment by rulaan** [comment]
Hi Robbinjanssen,

Trying to connect with JS/JSON/HTML gives:
[image: image.png]

Trying with TCP gives (note that a leading zero for the serial is stripped,
should be: 0602321995):
[image: image.png]

Testing  http://<inverter_IP>/js/status.js  on the Omnik-2.5k gives a
response as expected.
Testing  http://<inverter_IP>/js/status.js on the Omnik-3k gives a 404 Not
Found. No more info hidden in the html source.

Maybe the logger is too old to have more than just a landing page
(../home.html)?

Thanks for helping.

**Comment by robbinjanssen** [comment]
Hi @rulaan, unfortunately your images don't work. Can you try uploading them on github directly?

**Comment by htelgen** [comment]
I have the same problem. My other converter Omnik 1k is still connected

**Comment by robbinjanssen** [comment]
I'm afraid that if js/html doesn't work the only option is TCP. But that's kinda hard to debug (especially remotely). @MarijnS95 any idea on how we can get some debug info on this?

**Comment by MarijnS95** [comment]
@robbinjanssen I thought we looked into improving both the logging and status messages in the UI when currently "Can't connect" or "Unknown error" is displayed, but don't remember if that landed.

For starters, @rulaan @htelgen what appears in the Home Assistant logs right as `Unknown error occurred` is shown when attempting a connection through the TCP backend?

If that doesn't surface anything useful I'll recheck where the debug code went (and PR it back in), but we can always defer to something like [a filtered WireShark network capture](https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/121#issuecomment-1208217981) to inspect the exchanged data and go from there.

**Comment by remcovl92** [comment]
I have the same problem with Omniksol 3000TL. 
The data logger has firmware version 4.01.9.d1, maybe this is not supported in this firmware version?
@rulaan & @htelgen what firmware do you have?

**Comment by htelgen** [comment]
Where would I find that information?

Op za 15 okt. 2022 om 17:14 schreef Remco Vliegen ***@***.***

**Comment by remcovl92** [comment]
On the home page of the logger http://<inverter_IP>/home.html
then at the bottom of the page:
![image](https://user-images.githubusercontent.com/47039263/196031791-a771c741-f9ec-45fb-9d63-daa40829dcf7.png)

**Comment by htelgen** [comment]
My problem, at the moment, is that both my converters are not accessible
via Wifi anymore, so I don't get to the information.
I will try to reset the inverters (by cutting off the power) and try
accessing them again.

Op zo 16 okt. 2022 om 13:06 schreef Remco Vliegen ***@***.***

**Comment by robbinjanssen** [comment]
@remcovl92 @htelgen I doubt the firmware version matters. To properly assist you we need some more debugging logs like @MarijnS95 suggested in https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/129#issuecomment-1273093698 :-)

**Comment by htelgen** [comment]
I was able to connect to my 3000tl converter. It has ver:1.0.07
Any idea where to get an upgrade?

**Comment by robbinjanssen** [comment]
Converting this into a discussion as it is turning into a support thread ;-) Feel free to help each other out!
