### ISSUE TITLE
repositroy.json missing

### ISSUE THREAD

**Issue by jbr79** [robbinjanssen/home-assistant-omnik-inverter#13]
When adding the repository in HACS, the log shows the following error:

20-04-29 07:22:04 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/055ed765/repository.json: [Errno 2] No such file or directory: '/data/addons/git/055ed765/repository.json'
20-04-29 07:22:04 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/055ed765/repository.json

**Comment by robbinjanssen** [comment]
I think you are not adding it through HACS but you are adding it through hassio?

You need to add it via `/hacs/settings`

**Comment by jbr79** [comment]
ah for crying out loud... I need some time off.

Works!

**Comment by robbinjanssen** [comment]
Great to hear you resolved it, actually created a PR in HACS now to add it as a default repo :-)

**Comment by robbinjanssen** [comment]
To prevent this in the future, we've now been added as an official integration of HACS 🎉 

https://github.com/hacs/default/pull/383
