### ISSUE TITLE
Warning issue in 2023.2 - will fail in 2023.3 

### ISSUE THREAD

**Issue by ianfretwell** [robbinjanssen/home-assistant-omnik-inverter#145]
Warning error in HA logs after upgrade to 2023.2: - 

"Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for omnik_inverter using this method at custom_components/omnik_inverter/__init__.py, line 47: hass.config_entries.async_setup_platforms(entry, PLATFORMS)"

**Comment by robbinjanssen** [comment]
Try updating to the latest version, should be fixed!

**Comment by ianfretwell** [comment]
Yep - thanks!
