### ISSUE TITLE
Feature Request: Change login user and password (for html access)

### ISSUE THREAD

**Issue by marxram** [robbinjanssen/home-assistant-omnik-inverter#184]
Hello,

I use the integration via the HTML parser. It is setup once using IP, user and password of the device. 

After changing the password or username in the inverter, it was not possible to change the settings.

It would be great that theese settings can be changed / overwritten with new values.

**Comment by robbinjanssen** [comment]
I think home assistant default behaviour would be to remove and re-add the integration. But i'll see what I can do :)

**Comment by robbinjanssen** [comment]
Fixed in the latest release thanks to @raymanP
