### ISSUE TITLE
Error after HA Update

### ISSUE THREAD

**Issue by alenet** [robbinjanssen/home-assistant-omnik-inverter#211]
I own a Bosswerk mi600 and was using the Omnik over HTML to get the data to HA. Unfortunately after the latest update I am not able to get data from the micro inverter. 
I have access to the inverter and of course also can ping it. 

![image](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/1153008/a67af458-599b-448b-90a3-5e79a234a240)

Basically I can add the inverter into HA but it got no entities. Do you have any idea what can be the problem?
Thanks for your help

**Comment by robbinjanssen** [comment]
Is there any error in the HA log? Which version of HA do you use and which version of the integration?

**Comment by alenet** [comment]
Hi Robbin,
This is the HA Version
![image](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/1153008/33ea2491-9b9f-471f-825e-b22bdc341b2e)
This is the log file:
[home-assistant_omnik_inverter_2023-06-26T09-31-11.803Z.log](https://github.com/robbinjanssen/home-assistant-omnik-inverter/files/11866707/home-assistant_omnik_inverter_2023-06-26T09-31-11.803Z.log)

This should be the failure: 
2023-06-24 00:09:13.727 WARNING (MainThread) [homeassistant.config_entries] Config entry 'PVAnlage' for omnik_inverter integration not ready yet: Error occurred while communicating with Omnik Inverter device; Retrying in background

I dont know how to check the version of the integration. Can you help me there?

Thank you for your support  :)  As I´ve said, it worked so far as described in the installation but since the latest update this is happening. 
Best Regards,
Alejandro

**Comment by robbinjanssen** [comment]
Hi, seems like you are using an old version of the integration which has functionality home assistant no longer supports.

Try updating to the latest version using HACS or copy/pasting manually :)

**Comment by alenet** [comment]
Hi Robbin
![image](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/1153008/a3f375b7-721f-4abc-ae88-639d166f9400)

I´ve installed HACS again using the terminal.

![image](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/1153008/e4886a8b-a441-4712-abe8-a1cb8a71f9f9)

Restarted the Raspberry and the problem persist :(
Im not sure if I am doing everything right.

**Comment by robbinjanssen** [comment]
You've updated HACS, not the custom integration. 

You need to open HACS in your home assistant, click on "integrations", click on the big blue button bottom right (Explore & Download repositories) and then search for the `Omnik Inverter Solar Sensor (No Cloud)` integration.

Or alternatively; update [manually](https://github.com/robbinjanssen/home-assistant-omnik-inverter#manual-installation)

**Comment by alenet** [comment]
Problem Solved! Thank you Robbin!
Sorry for my incompetence :) 

PS: I will think twice next time I update HA. Everytime I do it something stops working.

**Comment by robbinjanssen** [comment]
Just keep everything up to date and you'll be fine :) HA has gotten really mature of the last few years, read release notes and look for potential breaking changes. In my experience keeping everything up to date gives you less problems in the future! :-)
