### ISSUE TITLE
Solar Energy Sensor (Day) provides weird values 

### ISSUE THREAD

**Issue by NCO3** [robbinjanssen/home-assistant-omnik-inverter#220]
## Detailed description
I am using a Bosswerk MI600 Solar inverter on the Omnik integration running:
`"home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.7.3",`
and `Omnik v2.6.1`
Because the Inverter goes offline when not powered by the sun (or by losing the wifi connection), some of the sensors show gaps.
One specific sensor (daily solar harvesting results) create some weird values then, which result in unrealistic jumps.
Consequently the calculation for the energy dashboard is messed up.

## Diagnostics
The problem is described here in detail:
https://community.home-assistant.io/t/help-interpreting-the-energy-dashboard/597581

If any more information is needed, just let me know.
Thank you for your contribution and support.

**Comment by robbinjanssen** [comment]
I see you are using the daily total as input for the dashboard sensor, may I recommend using the "total" production sensor? This is what I use and it works like a charm :)

**Comment by NCO3** [comment]
Of course you may @robbinjanssen 😊
Much appreciated
I will give it a try and report back.

**Comment by klaasnicolaas** [comment]
We do have to see what exactly happens to the data when the day value goes to 0. We can exclude this kind of behavior with an exception

**Comment by NCO3** [comment]
Hi Klaas,
Sounds good.
Please let me know what exactly you need and I will prepare whatever I can.

**Comment by robbinjanssen** [comment]
@NCO3 is your inverter unreachable (offline) or does it return `0` as a value?

**Comment by NCO3** [comment]
Or seems that the value 0 is correlated to the reconnection of the inverter:
![IMG_2389](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/15801364/6c094c42-a0c7-4b63-a9bd-3d06d41357b0)
The time stamp of the connection is the very same like the value going to 0.
This is true for several other occasions of 0

**Comment by klaasnicolaas** [comment]
@robbinjanssen we need to give him a custom version where every request data is logged, then we can see exactly what is happening.

**Comment by NCO3** [comment]
All,
Of course it would be nice to be fixed officially, but I found a workaround.
Please see here:
https://community.home-assistant.io/t/help-interpreting-the-energy-dashboard/597581/16
