### ISSUE TITLE
Component stops working after connection issues.

### ISSUE THREAD

**Issue by silvanverschuur** [robbinjanssen/home-assistant-omnik-inverter#25]
I've had this issues about 10 times now. When the inverter doesn't respond in time (within 10 seconds) or the component receives 'empty' data from the inverter the component stops working after some time. 

It seems like it's freezing (out of connections?). They only way to get it working again is to restart Home Assistant. In that case it looks like the component is preventing HA to shutdown because I have to kill the process manually from the command line. When I start HA again the component works fine.

These are the last lines of my `home-assistant.log` file

```2020-06-10 11:20:38 ERROR (SyncWorker_0) [custom_components.omnik_inverter.sensor] Empty data from Omnik Inverter 192.168.1.18
2020-06-10 12:08:21 ERROR (SyncWorker_1) [custom_components.omnik_inverter.sensor] Unable to fetch data from Omnik Inverter 192.168.1.18
2020-06-10 12:10:20 ERROR (SyncWorker_4) [custom_components.omnik_inverter.sensor] Empty data from Omnik Inverter 192.168.1.18
2020-06-10 12:20:28 ERROR (SyncWorker_1) [custom_components.omnik_inverter.sensor] Empty data from Omnik Inverter 192.168.1.18
2020-06-10 12:27:35 ERROR (SyncWorker_1) [custom_components.omnik_inverter.sensor] Empty data from Omnik Inverter 192.168.1.18
```

A couple of hours later I manually tried to open the web interface of the inverter and that worked fine.

**Comment by robbinjanssen** [comment]
Hi Sil, that's strange.. 

Not sure why this happens, the initial "result" data is set to [`None`](https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/master/custom_components/omnik_inverter/sensor.py#L132)

It then tries to fetch the data from the host by [opening, reading and closing the connection](https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/master/custom_components/omnik_inverter/sensor.py#L141-L143).

If it fails, then the result is still set to `None`. Then the sensors try to get the data by calling the [`update()`](https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/master/custom_components/omnik_inverter/sensor.py#L204) method. If the result is `None`, then it [returns False](https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/master/custom_components/omnik_inverter/sensor.py#L209-L211).

Not sure if I'm missing something here or doing it wrong.. I'll try to do some research if returning False is the way to go, but I don't see anything wrong with that atm.

Anyone else has an idea?

**Comment by silvanverschuur** [comment]
I might have an idea why it's going wrong. Suppose the connection can be established (`open`  call succeeds) but `data = json.load(fp)` fails. In that case an exception is caught but the connection isn't closed. 

I'm not a python programmer but I think you should use `try/except/finally` and move the `close` statement to the `finally` block to make sure the connection is always closed.

**Comment by robbinjanssen** [comment]
> I'm not a python programmer 

Same here 😂 
I'll see if i can find the time to write something, have been pretty busy lately

**Comment by robbinjanssen** [comment]
@silvanverschuur i've added the `finally` code block to always close the connection in v1.5.0
