### ISSUE TITLE
Hi i have a inverter Omnik 8000tl it's not on the list. did you have already the file to import value ?

### ISSUE THREAD

**Issue by Grenault76** [robbinjanssen/home-assistant-omnik-inverter#261]
## Diagnostics

```json
"Copy here the code or upload the file"
```

**Comment by Grenault76** [comment]
Hello, I just try the tree data sources possible

This that /js/status.js is the only method giving feedback see below
For the point 3 i have no idea where to find the downloadable diagnostic...

My best regards,
Gregory

192.168.1.17/js/status.js




var version= "H4.01.51MW.2.01W1.0.65(2018-02-271-D)";
var m2mMid = "639234596";
var wlanMac= "F0:FE:6B:C4:4E:20";
var m2mRssi= "100%";
var wanIp= "192.168.1.17";
var nmac= "F0FE6BC44E23";
var fephy= "off";
var yz_device_type="258";
var yz_device_num="1";
var init_inv_type="0";
var myDeviceArray=new Array();
myDeviceArray[0]="NLHN8020188M3006,V0.00Build,V6.01Build144,Omnik8000tl
,8000,0,779,304848,F00F01F02F03F04F05F06F07,1,";
;
function initPageText()
{
    var list = window.parent.reList("status");
    fileText("st1",list["t1"]);
    fileText("st2",list["t2"]);
    fileText("st3",list["t3"]);
    fileText("st4",list["t4"]);
    for(var i=1;i<=32;i++)
    {
        if(i!=14)
        {
            fileText("tx"+i,list[i]);
        }
    }
    init_main_page();
    initStatus();
    if(init_inv_type=="0")
    {
        hide("invTpDiv");
    }
    else
    {
        show("invTpDiv");
    }
    initInvList(parseInt(yz_device_type),yz_device_num);
    changeFont();
    child_getH();
}
function upfold(v)
{
    if(document.getElementById("up_"+v+"_div").style.display == "none")
    {
        show("up_"+v+"_div");
        document.getElementById("up_"+v).src = "image/up.png";
    }
    else
    {
        hide("up_"+v+"_div");
        document.getElementById("up_"+v).src = "image/down.png";
    }
    if(v == 3)
    {
        if(document.getElementById("ser_status").src=="")
        {
			//alert("mhtest");
            document.getElementById("ser_status").src="server_status.html";
        }
    }
}
function initInvList(type,num)
{
    if(type==null || type == "")
    {
        type = window.parent.reTip(40);
    }
    else
    {
        type = reInvBrand(type);
    }
    if(num==null || num == "")
    {
        hide("inv_msg_div");
        num = window.parent.reTip(40);
    }
    else
    {
        init_invdata_form();
    }
    var c = document.getElementById("inv_type");
    if(c)
    {
        c.innerHTML = type;
    }
    var d = document.getElementById("inv_num");
    if(d)
    {
        d.innerHTML = num;
    }
}
function init_main_page()
{
	var f=document.form_cover_setting;
	cfg2Form(f);
	var mac_1;
	var e;
	var on;
	var off;
	on=window.parent.reTip("1");
	off=window.parent.reTip("2");
	document.getElementById("cover_ver").innerHTML= version;
	document.getElementById("cover_mid").innerHTML= m2mMid;

	if (f.wifi_on.value== "disable")
	{
		document.getElementById("cover_ap_status").innerHTML= off;
		document.getElementById("cover_ap_mac").innerHTML= "";
		document.getElementById("cover_ap_ssid").innerHTML= "";
		document.getElementById("cover_ap_ip").innerHTML= "";

		document.getElementById("cover_sta_status").innerHTML= off;
		document.getElementById("cover_sta_rssi").innerHTML= "";
		document.getElementById("cover_sta_ip").innerHTML= "";
		document.getElementById("cover_sta_mac").innerHTML= "";
		document.getElementById("cover_sta_ssid").innerHTML= "";
	}
	else if (f.sta_enable.value== "1")
	{
		document.getElementById("cover_ap_status").innerHTML= on;
		document.getElementById("cover_ap_mac").innerHTML= wlanMac;
		document.getElementById("cover_ap_ssid").innerHTML= f.ap_ssid.value;
		document.getElementById("cover_ap_ip").innerHTML= f.lan_ip.value;

		document.getElementById("cover_sta_status").innerHTML= on;
		document.getElementById("cover_sta_rssi").innerHTML= m2mRssi;
		document.getElementById("cover_sta_ip").innerHTML= wanIp;
		mac_1= wlanMac.substring(0, 16);
		e= "0x"+ wlanMac.charAt(16);
		e= e*1+1;
		e= e.toString(16);
		e=e.toUpperCase();
		mac_1= mac_1+e;
		document.getElementById("cover_sta_mac").innerHTML= mac_1;
		document.getElementById("cover_sta_ssid").innerHTML= f.sta_ssid.value;
	}
	else
	{
		document.getElementById("cover_ap_status").innerHTML= on;
		document.getElementById("cover_ap_mac").innerHTML= wlanMac;
		document.getElementById("cover_ap_ssid").innerHTML= f.ap_ssid.value;
		document.getElementById("cover_ap_ip").innerHTML= f.lan_ip.value;

		document.getElementById("cover_sta_status").innerHTML= off;
		document.getElementById("cover_sta_rssi").innerHTML= "";
		document.getElementById("cover_sta_ip").innerHTML= "";
		document.getElementById("cover_sta_mac").innerHTML= "";
		document.getElementById("cover_sta_ssid").innerHTML= "";
	}
	
	if (fephy== "on")
	{
		document.getElementById("cover_cable_status").innerHTML= on;
		document.getElementById("cover_cable_ip").innerHTML= wanIp;
		document.getElementById("cover_cable_mac").innerHTML=
nmac.substring(0,2)+":"+nmac.substring(2,4)+":"+nmac.substring(4,6)+":"+nmac.substring(6,8)+":"+nmac.substring(8,10)+":"+nmac.substring(10,12);
	}
	else
	{
		document.getElementById("cover_cable_status").innerHTML= off;
		document.getElementById("cover_cable_ip").innerHTML= "";
		document.getElementById("cover_cable_mac").innerHTML= "";
	}
}

function init_invdata_form()
{
	var value= "";
	var con = document.getElementById("webdata_sn");
	con.innerHTML = "";
	if(con && myDeviceArray.length>0)
	{
	    show("inv_msg_div");
	    var inv_d = myDeviceArray[0].split(',');
	    for(var i=0; i<myDeviceArray.length;i++)
	    {
	        var option = document.createElement("option");
	        var data = myDeviceArray[i].split(',');
	        option.value = data[0];
	        option.innerHTML = data[0];
	        con.appendChild(option);
	    }
	    for(var i=1;i<inv_d.length;i++)
	    {
	        inv_data_show((i+1),inv_d[i]);
	    }
	}
	//var len, pos, nv;
	
	//alert(data);
//	len= data.length;
//	pos= 0;
//	nv= 0;
//	while (pos< len)
//	{
//		if (data.charAt(pos)== ',')
//		{
//			pos+=1;
//			nv+= 1;
//			web_data_show(nv, value);
//			value= "";
//		}
//		else
//		{
//			value= value+ data.charAt(pos);
//			pos+= 1;
//		}
//	}
}
function change_inv_list()
{
    var con = document.getElementById("webdata_sn");
    if(con)
    {

        var index = con.selectedIndex;
        if(myDeviceArray.length>index)
        {
            var inv_d = myDeviceArray[index].split(',');
            for(var i=1;i<inv_d.length;i++)
	        {
	            inv_data_show((i+1),inv_d[i]);
	        }
        }
    }
}
function inv_data_show(nv,value)
{
	var webdata_ids = new
Array("webdata_sn","webdata_msvn","webdata_ssvn","webdata_pv_type","webdata_rate_p","webdata_now_p","webdata_today_e","webdata_total_e","webdata_alarm","webdata_utime");
	
	if(nv>10||nv<=0)
	   return ;
	
	var elem = document.getElementById(webdata_ids[nv-1]);
	
	if(value==""&&elem!=null)
	{
		elem.innerHTML = "---";
		return;
	}
	if(elem!=null)
	{
		if (nv== 5)
			elem.innerHTML= value+" W";
		else if (nv== 6)
		{
		    if(value*1==4294967295)
		    {
		        elem.innerHTML = "---";
		    }
		    else
		    {
		        elem.innerHTML= value+" W";
		    }
		}
		else if (nv== 7)
		{
		    if(value*1==4294967295)
		    {
		        elem.innerHTML = "---";
		    }
		    else
		    {
			    sv= value*1/100;
			    elem.innerHTML= sv.toString()+" kWh";
			}
		}
		else if (nv== 8)
		{
		    if(value*1==4294967295)
		    {
		        elem.innerHTML = "---";
		    }
		    else
		    {
		        sv= value*1/10;
			    elem.innerHTML= sv.toString()+" kWh";
		    }
		}
		else if (nv== 10)
		{
			if (document.getElementById("webdata_sn").innerHTML== "---")
				elem.innerHTML = "---";
			else
				elem.innerHTML = value+window.parent.reTip("5");
		}
		else
			elem.innerHTML = value;
	}
	else
	{
		alert(webdata_ids[nv]);
	}
}





Le jeu. 7 déc. 2023 à 11:07, Robbin Janssen ***@***.***> a
écrit :

**Comment by robbinjanssen** [comment]
@Grenault76 great, this is the part we are interested in:
`myDeviceArray[0]="NLHN8020188M3006,V0.00Build,V6.01Build144,Omnik8000tl
,8000,0,779,304848,F00F01F02F03F04F05F06F07,1,";`

can you post this again, and then a screenshot with the actual values from the inverter?

**Comment by robbinjanssen** [comment]
See https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/267
