### ISSUE TITLE
buffer size too small (85 instead of at least 125 bytes)

### ISSUE THREAD

**Issue by Pakl8** [robbinjanssen/home-assistant-omnik-inverter#273]
buffer size too small (85 instead of at least 125 bytes) using TCP

## Detailed description
During the setup of the Omnik inverter, I used TCP as data source, filled in the host IP address and serial number, an error appears, see snaphot, any suggestions?
![TCP_error](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/46988410/759e2655-30bc-4a4e-9c6c-2c2acdeb95bb)

**Comment by MarijnS95** [comment]
I'm very sure we fixed this quite some time ago with https://github.com/klaasnicolaas/python-omnikinverter/pull/376

**Comment by klaasnicolaas** [comment]
But we need to bump the package, to fix it in the integration.

**Comment by Pakl8** [comment]
Thanks for your reaction, https://github.com/klaasnicolaas/python-omnikinverter is another package, I tried this one but had some issues during installation, this one was easier but run into a 3000TL inverter issue, which you explained.

**Comment by klaasnicolaas** [comment]
You are not supposed to install the package, because it is not an integration. The integration uses this pypi package to retrieve the data, if we have performed a version bump then this issue will be resolved.

**Comment by robbinjanssen** [comment]
Created a PR to bump the version: https://github.com/robbinjanssen/home-assistant-omnik-inverter/pull/276

**Comment by robbinjanssen** [comment]
@Pakl8 please try the latest version :)

**Comment by Pakl8** [comment]
For sure I must do something wrong, as I will get the same error, but I also do not see any changes in https://github.com/robbinjanssen/home-assistant-omnik-inverter/tree/main/custom_components/omnik_inverter exept for manifest.json, I used HACS by searching for Omnik Inverter Solar Sensor (No Cloud) to get things installed.

**Comment by robbinjanssen** [comment]
@MarijnS95 @klaasnicolaas are we sure this has been released? https://github.com/klaasnicolaas/python-omnikinverter/releases

**Comment by MarijnS95** [comment]
@robbinjanssen from the linked PR/commit there appears to be no tag pointing to it, so it wasn't released yet. Now `1.0.0` was published, and `1.0.0` shows up in the merge commit:

https://github.com/klaasnicolaas/python-omnikinverter/commit/b0498f228971c310d4a0cd5d626aa5a593280ea1

**Comment by robbinjanssen** [comment]
Released https://github.com/robbinjanssen/home-assistant-omnik-inverter/releases/tag/v2.6.4

**Comment by Pakl8** [comment]
Thanks for the update, works as it should be!
