### ISSUE TITLE
Unsupported Omnik converter

### ISSUE THREAD

**Issue by rdeherder** [robbinjanssen/home-assistant-omnik-inverter#303]
## Detailed description
I'm trying to add my Omnik converter. Two issues:
- I cannot connect using the HA setup. I get a "Cannot connect" error message. Perhaps this is because it needs authentication;
- When I log into the converter and try to fetch the js, json or status.html files I get a 404's back. Both on the internal and external ip address.

Converter info:
Type: Omniksol-2K-TL
Serial: 60222xxxx

Is this a known issue?

**Comment by robbinjanssen** [comment]
Hi,

There have been others who have successfully added the same inverter, see https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/15

Try looking in your network tab using the developer tools from where your inverter webpage fetches the data

**Comment by rdeherder** [comment]
Hi.

I looked at #15 and I saw a newer settings page than my inverter has:

![afbeelding](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/83836194/413c248f-57fb-4743-9ae0-026641d6f09b)

That probably means he/she has a newer inverter and would explain why trying to load the /js/status.js and /status.json files all end up in a 404 here.

The network tab when logging into my inverter:
![afbeelding](https://github.com/robbinjanssen/home-assistant-omnik-inverter/assets/83836194/ba235a4b-eea7-4bdc-a9fb-2ab6503055cf)

On the plus side, I have been able to get data from the inverter using the [Inverter-Data-Logger](https://github.com/XtheOne/Inverter-Data-Logger) package. Data is retreived from the inverter and sent to my account on pvoutput.org. HA then reads the data from there. Works fine, but since this is cloud based I prefer to use your solution.

**Comment by robbinjanssen** [comment]
You need to find out where your stats page on your inverter fetches the data from, might be a call to a JSON file in the network tab, or a JS file on page load.

If we know what the file and content is, we can add the support :)

**Comment by MarijnS95** [comment]
@rdeherder I'm quite sure I/we have have seen this settings page before. Have you tried the TCP backend option (which doesn't seem to be mentioned, only the file-base option)?

**Comment by MarijnS95** [comment]
Might have been https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/117, which also mentions TCP but before it was implemented in this package.

**Comment by rdeherder** [comment]
> @rdeherder I'm quite sure I/we have have seen this settings page before. Have you tried the TCP backend option (which doesn't seem to be mentioned, only the file-base option)?

I don't know what you mean with TCP backend option. Can you elaborate?

**Comment by MarijnS95** [comment]
@rdeherder this should be an option in the config flow when selecting the "Data source" from the dropdown.

**Comment by rdeherder** [comment]
Ok, that worked! Thanks very much for your help.
