### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'omnik_inverter'

### ISSUE THREAD

**Issue by wes1993** [robbinjanssen/home-assistant-omnik-inverter#31]
Hello,
In HA i have this warning now:

No 'version' key in the manifest file for custom integration 'omnik_inverter'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'omnik_inverter'

Best Regards
Stefano

**Comment by robbinjanssen** [comment]
Hi Stefano,

Thanks for reporting! I've added the version key to the manifest in v1.5.1, please update and the message will disappear :)

**Comment by wes1993** [comment]
Perfect!!! Thanks a lot
