### ISSUE TITLE
Integration not loaded in version 2024.7.1

### ISSUE THREAD

**Issue by Floriszz** [robbinjanssen/home-assistant-omnik-inverter#317]
## Detailed description
The error says that something wrong about import_module.
Same as other integrations HACS and native;
Google Nest: https://github.com/home-assistant/core/issues/121521
HACS pod_point : https://github.com/home-assistant/core/issues/121284

## Context
The integration won't load anymore after update from 2026.6.4 to 2024.7.1

## Diagnostics
Sorry, because I did a restore I can not get to the logs anymore

**Comment by klaasnicolaas** [comment]
Think I know what this is about, I'll make a bug fix

./Klaas

**Comment by klaasnicolaas** [comment]
Without logs it becomes difficult to determine where the problem is and how to solve it.

./Klaas

**Comment by Floriszz** [comment]
Sorry. Will update on my secondairy new rpi when it arrives🤞
It seems related to this issue;
https://github.com/home-assistant/core/issues/119223

**Comment by robbinjanssen** [comment]
Seems like a fix is incoming: https://github.com/home-assistant/core/pull/121782

**Comment by robbinjanssen** [comment]
Assuming this is fixed, i'm closing this issue
