### ISSUE TITLE
Can’t add Omnik 4k TLS-3 to Home Assistant

### ISSUE THREAD

**Issue by Joel81202** [robbinjanssen/home-assistant-omnik-inverter#319]
## Diagnostics

```json
"Copy here the code or upload the file"
```

**Comment by Joel81202** [comment]
I’m not able to find the webui with either JS, JSon or HTML. Can anyone please help me

**Comment by robbinjanssen** [comment]
Can you access the web interface of the inverter?

**Comment by Joel81202** [comment]
Hi Robbin. Ja kan ik

Grtz,
Michel van Wordragen
________________________________
Van: Robbin Janssen ***@***.***>
Verzonden: Wednesday, July 24, 2024 10:14:11 AM
Aan: robbinjanssen/home-assistant-omnik-inverter ***@***.***>
CC: Joel81202 ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [robbinjanssen/home-assistant-omnik-inverter] Can’t add Omnik 4k TLS-3 to Home Assistant (Issue #319)


Can you access the web interface of the inverter?

**Comment by robbinjanssen** [comment]
Can you provide a screenshot of the webinterface with the stats?
