### ISSUE TITLE
Omink liquidation closedown omnikportal 

### ISSUE THREAD

**Issue by edegraaff** [robbinjanssen/home-assistant-omnik-inverter#34]
Hi, as most of us have been informed omnik is not able to pay for the hosting services. This is now done by Solarman, you need to pay for their services. 

Is it possible to no change the code in a way, the data is directly pulled from the inverter? 

and or make use of traffic over the wifi network?

**Comment by robbinjanssen** [comment]
Hi @edegraaff,

This component doesn't depend on any cloud services like Solarman. It connects to your inverter directly and reads the data from there :-)
