### ISSUE TITLE
Weird behavior when reading from two inverters

### ISSUE THREAD

**Issue by hepfister** [robbinjanssen/home-assistant-omnik-inverter#36]
I have two inverters that I read using:
```
# Omnik Inverter 3k
  - platform: omnik_inverter
    host: 192.168.1.248
# Omnik Inverter 1.5K
  - platform: omnik_inverter
    host: 192.168.1.249
```
HA creates unique ID's, for example 'sensor.solar_power_today' and 'sensor.solar_power_today_2'. Yet, the data showed for 'sensor.solar_power_today_2' is the same as 'sensor.solar_power_today'. I know for a fact this amount should be very different.

The odd thing is that it only happens with 'sensor.solar_power_today'. 

'sensor.solar_power_total(_2)' and 'sensor.solar_power_current(_2)' are showing their correct values per inverter. Perhaps this is just luck?

I read in a different issue that the ID's are not pre-defined, but created dynamically when the inverter becomes online. Could this cause this issue when reading from >1 inverters with this plugin?

**Comment by robbinjanssen** [comment]
Hi @hepfister, I think what you are describing is spot on. Could you try adding a 'name' (thanks to @Rmvandiepen in https://github.com/robbinjanssen/home-assistant-omnik-inverter/pull/35) to your config for each inverter? This will used when defining the entity names, that might resolve your issue!

**Comment by Rmvandiepen** [comment]
Found one small problem with the cache when using multiple inverters (the today_cache is shared between both inverters). Should be resolved by #37

**Comment by robbinjanssen** [comment]
Awesome @Rmvandiepen! I've tagged 1.5.4 :)

**Comment by hepfister** [comment]
@robbinjanssen, sorry for responding late. The 'name' suggestion works well. Testing your plugin alongside the other Omnik integration (which has problems on its own). Hope to replace it with your lighter weight implementation. Thanks for fixing the issue :)
