### ISSUE TITLE
change power to energy

### ISSUE THREAD

**Issue by sander76** [robbinjanssen/home-assistant-omnik-inverter#42]
A bit of nitpicking,

But kWh is a unit of energy not power.

https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/06c87de448ee5e76dc915827a1dbdbe7dd6d6be0/custom_components/omnik_inverter/sensor.py#L47

https://github.com/robbinjanssen/home-assistant-omnik-inverter/blob/06c87de448ee5e76dc915827a1dbdbe7dd6d6be0/custom_components/omnik_inverter/sensor.py#L48

**Comment by klaasnicolaas** [comment]
That will be fixed in the next BIG future release.
