### ISSUE TITLE
No data inverter

### ISSUE THREAD

**Issue by ErikTbk** [robbinjanssen/home-assistant-omnik-inverter#65]
Hi,

I have a Omnik 2.0 TL3-S inverter. 
When I do the configuration I get the error code: Error occurred while communicating with Omnik Inverter device.

I have tried the three options below, but no result.
- Most inverters have a JS file, try accessing http://<your omnik ip address>/js/status.js in your browser.
- Some inverters use a JSON status file to output the values. Check if your inverter outputs JSON data by navigating to: http://<your omnik ip address>/status.json?CMD=inv_query.
- A few inverters dont have JS or JSON but output the values directly in a HTML files. Check if your inverter supports the following URL: http://<your omnik ip address>/status.html. Note that this will work for almost all inverters, but you need to check the HTML source for a <script> tag that contains the relevant webData.

Any idea how I can receive data

**Comment by robbinjanssen** [comment]
Hi @ErikTbk,

Can you try inspecting using the developer tools of your browser if the data is present?
Check the network tab and look for the relevant webData. If it is visible in a file somewhere we can probably parse it.

If you need help feel free to reach out, we'll invite you to our slack channel and we might be able to help using teamviewer or if you are brave enough open up your inverter to the internet temporarily :-)

**Comment by robbinjanssen** [comment]
Closing for now, feel free to reach out at r.janssen@exonet.nl if you need more help debugging :-)
