### ISSUE TITLE
2 inverters

### ISSUE THREAD

**Issue by WHagenauw** [robbinjanssen/home-assistant-omnik-inverter#66]
How to handle 2 inverters? I know have added 2 inverters but in the graph they will stand next to each other. Can I get it as a total and add it to the new energy dashboard? If I create a ne sensor I cannot add it to the new energy dashboard.....

**Comment by WHagenauw** [comment]
That's correct. Now you see 2 graphs next to each other but not the total
in the graph. The forecast also seems to be from 1 inverter. The graph with
the circles is showing the total.

[image: image.png]

Op di 12 okt. 2021 om 09:06 schreef Robbin Janssen ***@***.***

**Comment by klaasnicolaas** [comment]
In the next big release of Home Assistant core the bars will be stacked 😉
