### ISSUE TITLE
Not connecting to Ginlong Solis

### ISSUE THREAD

**Issue by beestarbush** [robbinjanssen/home-assistant-omnik-inverter#70]
Hello,

I have been trying to add a Ginlong Solis inverter with a Ginlong stick but when using the "Integration Add..." button it failed to add and displays the error "Kon niet verbinden"/"Could not connect". The data is retrievable via JS and via JSON and if needed I could post that here. Could you help me with this?

Thanks.

**Comment by klaasnicolaas** [comment]
No no no no no this is not stale 😅
