### ISSUE TITLE
Ginlong stick password

### ISSUE THREAD

**Issue by kongjudas** [robbinjanssen/home-assistant-omnik-inverter#77]
Get "Failed to connect". I have probably overseen something basic here, but when I try to access my Ginlong stick via the browser, I'm asked for user/ password. I can't see how the integration could get pass that with the GUI installation using JSON (I understand that is the correct mode, as you stated in the docs).

**Comment by klaasnicolaas** [comment]
What do you see when you go to this page? Do you also have to log in? 
`http://<your omnik ip address>/status.json?CMD=inv_query`

**Comment by kongjudas** [comment]
ERROR:404 Not Found

**Comment by klaasnicolaas** [comment]
There is really no way to determine how those Ginlong sticks work :(, it works differently for everyone, making support for them extra difficult.

**Comment by kongjudas** [comment]
Well, I've found that it serves the data thru HTML. So far so good, but no cigar.

**Comment by robbinjanssen** [comment]
@kongjudas can you output the data that is served by the Inverter? Maybe that differs from what we expect?
