### ISSUE TITLE
No data from Omnik3000TL inverter.

### ISSUE THREAD

**Issue by NewQuichotte** [robbinjanssen/home-assistant-omnik-inverter#80]
Hello, I have an Omnik Omnik3000tl the readout does not seem to work.
Does this inverter have any capabilities?

**Comment by klaasnicolaas** [comment]
That depends on whether one of the 3 sources works with your inverter, or maybe there is a 4th option that we don't know yet. https://github.com/robbinjanssen/home-assistant-omnik-inverter#what-data-source-do-i-use

**Comment by hepfister** [comment]
I have the same inverter and can confirm that this plugin works.

**Comment by klaasnicolaas** [comment]
And what source did it work with? Because then we could put this one on the list that it works 😉

**Comment by NewQuichotte** [comment]
Omnik3000TL javascript

**Comment by robbinjanssen** [comment]
@NewQuichotte so it works for you now? We can close this issue? :)

**Comment by NewQuichotte** [comment]
Yes, and thanks.
