### ISSUE TITLE
Feature request: Add automated upload functionality to PVoutput.org

### ISSUE THREAD

**Issue by hepfister** [robbinjanssen/home-assistant-omnik-inverter#99]
## Detailed description
HA recently got a data consumer integration to fetch information from PVOutput (which was uploaded by your solar photovoltaic (PV) system). It got me thinking that it would be nice of this omnik plugin has the option to push data to PVOutput.org.

## Context
This feature could secure our PV data, as it could serve as a backup. I'm a HA user for almost 2 years now and have lost most of my PV data collected over this time due to user error and 'bugs'. Migration from SD to SSD, from NAS to Raspberry, going from SQLite to MariaDB. I guess things many users do, but not oversea the consequences of their 'playing around' until the data is already lost.

**Comment by klaasnicolaas** [comment]
It would be a good idea to see if we can upload that data to PVoutput. The functionality would then have to be created in the [python package](https://github.com/klaasnicolaas/python-omnikinverter) and the interval execution in the integration.

I'm just not that familiar with the platform myself and how easy it is to push that data to the platform.

**Comment by robbinjanssen** [comment]
@hepfister I understand your problem, but I don't think its within the scope of this component. This is purely a "read data form inverter and sent to HA"-component. If we start supporting sites like PVoutput, who knows where it will end.

I think you should take a look at https://github.com/Woutrrr/Omnik-Data-Logger, it's a python script that does exactly what you want I think :)
